version: '3.9'

services:   
  keyforger-database:
    container_name: keyforger-database
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=keyforger
        - MYSQL_USER=keyforger
        - MYSQL_PASSWORD=password
    command: 
        - --table_definition_cache=100
        - --performance_schema=0
        - --default-authentication-plugin=mysql_native_password
        - --innodb_use_native_aio=0
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
        - ./mysql-data:/var/lib/mysql
  
  keyforger-queue:
    container_name: keyforger-queue
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
